// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYtveOnvyWCVYtT_mAfk_1aeQaAGYAllA',
    appId: '1:229828936184:web:a1938218aab32248d8160d',
    messagingSenderId: '229828936184',
    projectId: 'ml8monitors',
    authDomain: 'ml8monitors.firebaseapp.com',
    storageBucket: 'ml8monitors.appspot.com',
    measurementId: 'G-JNP673WQ17',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvzkifKtqEPT_Adp2rOAhOosLxVW4yE2U',
    appId: '1:229828936184:android:9840f2f266a53496d8160d',
    messagingSenderId: '229828936184',
    projectId: 'ml8monitors',
    storageBucket: 'ml8monitors.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-RCTKvUpIW7q2gWbajSa5l_qkF7FLRR8',
    appId: '1:229828936184:ios:7dfdf3303e1d644bd8160d',
    messagingSenderId: '229828936184',
    projectId: 'ml8monitors',
    storageBucket: 'ml8monitors.appspot.com',
    iosClientId: '229828936184-pghafpv8ksb4ak13pu8voojspfv9sj6l.apps.googleusercontent.com',
    iosBundleId: 'com.michaellee8.ml8monitors',
  );
}
